const {chromium}=require('C:/Users/Mark/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/tests/animation.html');
 await page.waitForSelector('.track-name');
 await page.locator('.track-name').filter({hasText:'Young Man'}).click();
 await page.getByLabel('Movement preset').selectOption('enter-left');
 await page.getByLabel('Camera move',{exact:true}).selectOption('push-in');
 assert.equal(await page.locator('.key-marker').count(),2);
 await page.evaluate(async()=>{window.editorStore.getState().seek(1.2);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
 await page.screenshot({path:'outputs/animation-desktop.png'});
 const a=await page.locator('.canvas-wrap canvas').screenshot();
 await page.evaluate(async()=>{window.editorStore.getState().seek(1.8);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
 const b=await page.locator('.canvas-wrap canvas').screenshot();assert.notDeepEqual(a,b);
 await page.getByLabel('Add keyframe',{exact:true}).click();
 const keysBefore=await page.locator('.key-marker').count();assert.equal(keysBefore,3);
 const marker=page.locator('.key-marker').nth(1), box=await marker.boundingBox();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2-65,box.y+box.height/2);await page.mouse.up();
 const times=await page.evaluate(()=>window.editorStore.getState().project.shots[0].objects.find(o=>o.kind==='character').keyframes.map(k=>k.time));
 assert.ok(times[1]<1.8);
 await page.getByRole('button',{name:'Time Card',exact:true}).click();
 await page.locator('textarea').fill('5 seconds later...');
 assert.equal(await page.locator('textarea').inputValue(),'5 seconds later...');
 await page.screenshot({path:'outputs/animation-time-card.png'});
 await page.evaluate(async()=>{
   const s=window.editorStore,assets=window.editorAssets;
   const state=s.getState();state.addShot();
   state.addAssetToActiveShot(assets.find(x=>x.id==='bg-kitchen'));
   const shot=s.getState().project.shots.at(-1), actor=shot.objects.find(x=>x.kind==='character');
   s.getState().updateObject(shot.objects.find(x=>x.kind==='background').id,{atmosphere:'dust'});
   s.getState().applyMotion(actor.id,'approach');s.getState().applyCameraMotion('push-in');
   s.getState().addAssetToActiveShot(assets.find(x=>x.id==='prop-pizza'),630,1120);
   s.getState().addAssetToActiveShot(assets.find(x=>x.id==='prop-plant'),30,1070);
   s.getState().selectObject(actor.id);
 });
 const project=await page.evaluate(()=>{const p=structuredClone(window.editorStore.getState().project);p.name='Animation Playground';p.activeShotId=p.shots[0].id;return p;});
 fs.writeFileSync('outputs/animation-playground.json',JSON.stringify(project,null,2));
 await page.getByRole('button',{name:'Props',exact:true}).click();
 await page.getByRole('button',{name:'Play',exact:true}).click();
 await page.waitForTimeout(250);
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 const stopped=await page.evaluate(()=>window.editorStore.getState().playhead);
 await page.waitForTimeout(150);
 assert.equal(await page.evaluate(()=>window.editorStore.getState().playhead),stopped);
 await page.screenshot({path:'outputs/animation-props.png'});
 await page.setViewportSize({width:800,height:900});await page.screenshot({path:'outputs/animation-tablet.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'outputs/animation-mobile.png'});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser checks passed: keyframe controls, canvas movement, time-card editing, new props, desktop/tablet/mobile screenshots.');
})().catch(e=>{console.error(e);process.exit(1)});
