const assert = require('node:assert/strict');
global.crypto = require('node:crypto').webcrypto;
const { buildSync } = require('esbuild');
function load(entry) {
 const output=buildSync({entryPoints:[entry],bundle:true,platform:'node',format:'cjs',write:false});
 const mod={exports:{}};new Function('require','module','exports',output.outputFiles[0].text)(require,mod,mod.exports);return mod.exports;
}
const {useEditorStore:store}=load('src/store/editorStore.ts');
const {objectAt,cameraAt}=load('src/animation.ts');
const s=()=>store.getState();
const original=JSON.parse(JSON.stringify(s().project));
const shot=()=>s().project.shots.find(x=>x.id===s().project.activeShotId);
const actor=()=>shot().objects.find(x=>x.kind==='character');
const id=actor().id, x=actor().transform.x;
s().setAutoKey(true);s().seek(1);s().updateObjectTransform(id,{x:x+200});
assert.equal(actor().keyframes.length,2);
assert.equal(objectAt(actor(),0).transform.x,x);
assert.equal(objectAt(actor(),.5).transform.x,x+100);
s().updateObject(id,{expression:'shocked'});
assert.equal(objectAt(actor(),.9).expression,'neutral');
assert.equal(objectAt(actor(),1).expression,'shocked');
s().setKeyEasing(id,0,'hold');
assert.equal(objectAt(actor(),.9).transform.x,x);
s().setKeyEasing(id,0,'linear');
assert.equal(objectAt(actor(),.25).transform.x,x+50);
s().applyCameraMotion('push-in');
assert.ok(cameraAt(shot(),1).zoom>1);
const beforeObject=objectAt(actor(),1.2).transform;
const beforeCamera=cameraAt(shot(),1.2);
s().seek(.8);s().splitShot();
assert.equal(shot().animationOffset,.8);
assert.deepEqual(objectAt(actor(),shot().animationOffset+.4).transform,beforeObject);
assert.ok(Math.abs(cameraAt(shot(),1.2).zoom-beforeCamera.zoom)<1e-8);
const split=JSON.parse(JSON.stringify(s().project));
s().loadProject(JSON.parse(JSON.stringify(split)));
assert.deepEqual(s().project,split);
s().setCanvasSize(1920,1080);s().setCanvasSize(1080,1920);
assert.deepEqual(actor().transform,split.shots[1].objects.find(x=>x.kind==='character').transform);
s().loadProject(original);s().setAutoKey(false);s().seek(0);
s().applyMotion(id,'enter-left');
assert.ok(objectAt(actor(),0).transform.x<0);
assert.equal(objectAt(actor(),0).action,'walking');
assert.equal(objectAt(actor(),2.5).transform.x,x);
const last=actor().keyframes[1].time;
s().moveKeyframe(id,last,1.5);assert.ok(actor().keyframes.some(k=>k.time===1.5));
s().deleteKeyframe(id,1.5);assert.equal(actor().keyframes.length,1);s().undo();assert.equal(actor().keyframes.length,2);
s().selectObject(id);s().duplicateSelected();
const copy=shot().objects.find(o=>o.id===s().selectedIds[0]);
assert.equal(copy.keyframes[0].transform.x,actor().keyframes[0].transform.x+42);
s().loadProject(original);s().addAudio({id:'voice',name:'Voice',source:'data:audio/wav;base64,test',sourceDuration:1,start:3,trimStart:0,duration:1,volume:1,muted:false});
s().setShotDuration(2.5);
s().addTimeCard();assert.equal(shot().objects[0].assetId,'bg-time-card');assert.equal(shot().duration,2);
assert.equal(s().project.audioClips[0].start,5);
assert.equal(shot().objects[1].text,'5 seconds later...');s().undo();assert.equal(s().project.shots.length,1);
console.log('Animation checks passed: interpolation, pose cuts, easing, camera, split continuity, round-trip, aspect ratio, movement, retiming, undo and time cards.');
