const assert = require('node:assert/strict');
global.crypto = require('node:crypto').webcrypto;
const { buildSync } = require('esbuild');
const output = buildSync({ entryPoints: ['src/store/editorStore.ts'], bundle: true, platform: 'node', format: 'cjs', write: false });
const mod = { exports: {} };
new Function('require', 'module', 'exports', output.outputFiles[0].text)(require, mod, mod.exports);
const store = mod.exports.useEditorStore;
const state = () => store.getState();
const original = JSON.parse(JSON.stringify(state().project));
const clip = { id: 'audio-test', name: 'Narration', source: 'data:audio/wav;base64,test', sourceDuration: 10, start: 1, trimStart: 0, duration: 10, volume: 1, muted: false };
state().addAudio(clip);
assert.equal(state().project.audioClips[0].source, clip.source);
assert.ok(state().project.shots.reduce((sum, shot) => sum + shot.duration, 0) >= 11);
state().updateAudio(clip.id, { trimStart: 8, duration: 9, volume: 2, start: -1 });
assert.deepEqual([state().project.audioClips[0].trimStart, state().project.audioClips[0].duration, state().project.audioClips[0].volume, state().project.audioClips[0].start], [8, 2, 1, 0]);
state().updateAudio(clip.id, { start: NaN });
assert.equal(state().project.audioClips[0].start, 0);
state().updateAudio(clip.id, { start: 20, muted: true });
assert.ok(state().project.shots.reduce((sum, shot) => sum + shot.duration, 0) >= 22);
state().deleteAudio(clip.id);
assert.equal(state().project.audioClips.length, 0);
state().undo();
assert.equal(state().project.audioClips[0].muted, true);
const saved = JSON.parse(JSON.stringify(state().project));
state().loadProject(original);
assert.equal(state().project.audioClips, undefined);
state().loadProject(saved);
assert.equal(state().project.audioClips[0].source, clip.source);
state().seek(1);
state().splitShot();
assert.equal(state().project.audioClips[0].start, 20);
console.log('Audio checks passed: timing, trim limits, volume limits, undo, project round-trip, and shot split independence.');
