const assert = require('node:assert/strict');
global.crypto = require('node:crypto').webcrypto;
const { buildSync } = require('esbuild');
const output = buildSync({ entryPoints: ['src/store/editorStore.ts'], bundle: true, platform: 'node', format: 'cjs', write: false });
const mod = { exports: {} };
new Function('require', 'module', 'exports', output.outputFiles[0].text)(require, mod, mod.exports);
const store = mod.exports.useEditorStore;
const state = () => store.getState();
const original = JSON.parse(JSON.stringify(state().project));
state().seek(1);
state().splitShot();
assert.deepEqual(state().project.shots.map(s => s.duration), [1, 1.5]);
assert.equal(state().project.shots[1].animationOffset, 1);
assert.equal(state().playhead, 1);
assert.notEqual(state().project.shots[0].objects[0].id, state().project.shots[1].objects[0].id);
state().seek(.5);
assert.equal(state().project.activeShotId, state().project.shots[0].id);
state().seek(1);
assert.equal(state().project.activeShotId, state().project.shots[1].id);
state().splitShot();
assert.equal(state().project.shots.length, 2);
state().undo();
assert.deepEqual(state().project, original);
state().redo();
assert.equal(state().project.shots.length, 2);
state().setShotDuration(NaN);
assert.equal(state().project.shots[1].duration, 1.5);
state().setShotDuration(1 / 30);
assert.equal(state().project.shots[1].duration, 1 / 30);
const [first, second] = state().project.shots;
state().setShotTransition(first.id, 'wipe', .4);
assert.equal(state().project.shots[0].transition, 'wipe');
assert.equal(state().project.shots[0].transitionDuration, .4);
state().duplicateShot(first.id);
assert.equal(state().project.shots[1].name, `${first.name} Copy`);
assert.equal(state().project.activeShotId, state().project.shots[1].id);
assert.notEqual(state().project.shots[1].objects[0].id, first.objects[0].id);
state().undo();
state().moveShot(second.id, first.id);
assert.equal(state().project.shots[0].id, second.id);
state().seek(999);
assert.equal(state().playhead, 1 + 1 / 30);
state().deleteShot(first.id);
assert.equal(state().project.shots.length, 1);
state().deleteShot(second.id);
assert.equal(state().project.shots.length, 1);
console.log('Timeline checks passed: split continuity, boundaries, undo/redo, trim, reorder, seek, delete.');
